-- SQL Seed Script for global_restaurants
-- Generated by Neighborhood Explorer CLI Export
INSERT INTO global_restaurants (
    id, name, description, cuisine_type, price_level, lat, lng, address, 
    cover_image_url, is_promoted, promotion_end_at, created_at, updated_at, 
    likes_count, views_count
) VALUES
    ('d28ded0e-9d8b-4499-b8cf-111026eef285', 'Zelai Sevilla Este', 'Deliciosa comida', 'Tapas', 2, 37.404845, -5.92812, 'Calle Alcalde Luis Uruñuela, 16, 41020 Sevilla', 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5', false, NULL, '2026-07-08T10:06:00Z', '2026-07-08T10:06:44Z', 0, 0);