import os
import sys
import json
import streamlit as st
import folium
from streamlit_folium import st_folium
import pandas as pd

# Add src directory to path
sys.path.append(os.path.dirname(os.path.abspath(__file__)))
import database

# Initialize database schema on startup
database.init_db()

# Page configuration
st.set_page_config(
    page_title="Neighborhood Explorer",
    page_icon="📍",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Custom premium styling
st.markdown("""
<style>
    .main-title {
        font-family: 'Outfit', 'Inter', sans-serif;
        font-weight: 800;
        color: #FF4B4B;
        margin-bottom: 5px;
    }
    .subtitle {
        font-family: 'Inter', sans-serif;
        color: #555555;
        font-size: 1.1rem;
        margin-bottom: 25px;
    }
    .card {
        background-color: #f9f9f9;
        padding: 20px;
        border-radius: 10px;
        box-shadow: 0 4px 6px rgba(0,0,0,0.05);
        margin-bottom: 15px;
    }
    .metric-val {
        font-size: 1.8rem;
        font-weight: bold;
        color: #333;
    }
    .metric-lbl {
        font-size: 0.9rem;
        color: #777;
        text-transform: uppercase;
        letter-spacing: 1px;
    }
</style>
""", unsafe_allow_html=True)

# Workspace directories setup
WORKSPACE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
UPLOAD_DIR = os.path.join(WORKSPACE_DIR, "data", "images")
os.makedirs(UPLOAD_DIR, exist_ok=True)

def get_absolute_image_path(path):
    if not path:
        return None
    if os.path.isabs(path):
        return path
    return os.path.join(WORKSPACE_DIR, path)

def save_uploaded_file(uploaded_file, restaurant_id):
    """Saves uploaded file to UPLOAD_DIR and returns the relative path."""
    if uploaded_file is None:
        return None
    _, ext = os.path.splitext(uploaded_file.name)
    if not ext:
        ext = ".png"
    filename = f"{restaurant_id}{ext}"
    file_path = os.path.join(UPLOAD_DIR, filename)
    with open(file_path, "wb") as f:
        f.write(uploaded_file.getbuffer())
    return f"data/images/{filename}"

def load_preview_image(image_path_or_url):
    """Checks if the path is a URL or a valid local file and returns it for display."""
    if not image_path_or_url:
        return None
    if image_path_or_url.startswith("http://") or image_path_or_url.startswith("https://"):
        return image_path_or_url
    abs_path = get_absolute_image_path(image_path_or_url)
    if abs_path and os.path.exists(abs_path):
        return abs_path
    return None

# Helper functions for export
def convert_to_export_format(restaurants):
    """Converts SQLite integer booleans and other fields to final schema format."""
    exported = []
    for r in restaurants:
        r_dict = dict(r)
        # Convert SQLite is_promoted integer to boolean
        r_dict["is_promoted"] = True if r_dict.get("is_promoted") == 1 else False
        # Remove explorer specific fields
        r_dict.pop("validation_status", None)
        r_dict.pop("neighborhood", None)
        r_dict.pop("osm_id", None)
        exported.append(r_dict)
    return exported

def generate_sql_seed(restaurants):
    """Generates PostgreSQL INSERT statements matching the target global_restaurants schema."""
    if not restaurants:
        return ""
        
    sql_lines = [
        "-- SQL Seed Script for global_restaurants",
        "-- Generated by Neighborhood Explorer",
        "INSERT INTO global_restaurants (",
        "    id, name, description, cuisine_type, price_level, lat, lng, address, ",
        "    cover_image_url, is_promoted, promotion_end_at, created_at, updated_at, ",
        "    likes_count, views_count",
        ") VALUES"
    ]
    
    value_rows = []
    for r in restaurants:
        def escape(val):
            if val is None:
                return "NULL"
            escaped = str(val).replace("'", "''")
            return f"'{escaped}'"
            
        r_id = escape(r.get("id"))
        name = escape(r.get("name"))
        desc = escape(r.get("description"))
        cuisine = escape(r.get("cuisine_type"))
        price = str(r.get("price_level")) if r.get("price_level") is not None else "NULL"
        lat = str(r.get("lat"))
        lng = str(r.get("lng"))
        addr = escape(r.get("address"))
        cover = escape(r.get("cover_image_url"))
        is_promoted = "true" if r.get("is_promoted") == 1 else "false"
        prom_end = escape(r.get("promotion_end_at"))
        created = escape(r.get("created_at"))
        updated = escape(r.get("updated_at"))
        likes = str(r.get("likes_count") or 0)
        views = str(r.get("views_count") or 0)
        
        row_str = f"    ({r_id}, {name}, {desc}, {cuisine}, {price}, {lat}, {lng}, {addr}, {cover}, {is_promoted}, {prom_end}, {created}, {updated}, {likes}, {views})"
        value_rows.append(row_str)
        
    sql_lines.append(",\n".join(value_rows) + ";")
    return "\n".join(sql_lines)

# Application Layout
st.markdown("<h1 class='main-title'>📍 Neighborhood Explorer</h1>", unsafe_allow_html=True)
st.markdown("<p class='subtitle'>Review, validate, and export neighborhood restaurants for the FoodieDot application.</p>", unsafe_allow_html=True)

# Database Connection
conn = database.get_db_connection()

# Sidebar Statistics & Filters
with st.sidebar:
    st.header("📊 Explorer Dashboard")
    
    # Query status counts
    cur = conn.cursor()
    cur.execute("SELECT validation_status, COUNT(*) as cnt FROM candidate_restaurants GROUP BY validation_status")
    counts = {row["validation_status"]: row["cnt"] for row in cur.fetchall()}
    
    pending_count = counts.get("pending", 0)
    valid_count = counts.get("valid", 0)
    invalid_count = counts.get("invalid", 0)
    total_count = pending_count + valid_count + invalid_count
    
    st.markdown(f"""
    <div class="card">
        <div class="metric-val">{total_count}</div>
        <div class="metric-lbl">Total Discovered</div>
    </div>
    <div class="card" style="border-left: 5px solid #ffa500;">
        <div class="metric-val" style="color: #ffa500;">{pending_count}</div>
        <div class="metric-lbl">Pending Review</div>
    </div>
    <div class="card" style="border-left: 5px solid #28a745;">
        <div class="metric-val" style="color: #28a745;">{valid_count}</div>
        <div class="metric-lbl">Approved (Valid)</div>
    </div>
    <div class="card" style="border-left: 5px solid #dc3545;">
        <div class="metric-val" style="color: #dc3545;">{invalid_count}</div>
        <div class="metric-lbl">Rejected (Invalid)</div>
    </div>
    """, unsafe_allow_html=True)
    
    st.divider()
    
    # Neighborhood filter
    cur.execute("SELECT DISTINCT neighborhood FROM candidate_restaurants")
    hoods = [row["neighborhood"] for row in cur.fetchall()]
    if not hoods:
        hoods = ["Sevilla Este"]
    selected_hood = st.selectbox("Active Neighborhood", hoods)

# Tabs definitions
tab_pending, tab_approved, tab_rejected = st.tabs([
    "📥 Pending Candidates", 
    "✅ Approved Restaurants", 
    "❌ Rejected Restaurants"
])

# ==========================================
# 📥 TAB 1: PENDING CANDIDATES
# ==========================================
with tab_pending:
    pending_list = database.get_restaurants_by_status(conn, "pending", selected_hood)
    
    if not pending_list:
        st.info("🎉 All caught up! There are no pending candidate restaurants to review for this neighborhood.")
        st.markdown("""
        **Next Steps:**
        1. Use the instructions in `prompt.md` to run an AI agent to search and seed more restaurants.
        2. Select a different neighborhood in the sidebar if available.
        """)
    else:
        # Master list selector
        names = [r["name"] for r in pending_list]
        selected_index = st.selectbox(
            "Select Restaurant to Review", 
            range(len(names)), 
            format_func=lambda idx: f"{names[idx]} (OSM: {pending_list[idx].get('osm_id') or 'N/A'})"
        )
        
        selected_rest = pending_list[selected_index]
        
        # Details Form
        st.subheader(f"Reviewing: {selected_rest['name']}")
        
        # Two-column layout for details & preview
        col_form, col_preview = st.columns([3, 2])
        
        with col_form:
            with st.form("review_form", clear_on_submit=False):
                # Edit fields
                name_val = st.text_input("Name (Required)", value=selected_rest["name"])
                description_val = st.text_area("Description", value=selected_rest["description"] or "")
                cuisine_val = st.text_input("Cuisine Type", value=selected_rest["cuisine_type"] or "")
                price_val = st.number_input("Price Level (1-4)", min_value=1, max_value=4, value=selected_rest["price_level"] or 2, step=1)
                
                # Coordinates
                col_lat, col_lng = st.columns(2)
                with col_lat:
                    lat_val = st.number_input("Latitude", value=float(selected_rest["lat"]), format="%.6f")
                with col_lng:
                    lng_val = st.number_input("Longitude", value=float(selected_rest["lng"]), format="%.6f")
                    
                address_val = st.text_input("Address", value=selected_rest["address"] or "")
                cover_val = st.text_input("Cover Image URL", value=selected_rest["cover_image_url"] or "")
                uploaded_file = st.file_uploader("Or Upload Cover Image File", type=["png", "jpg", "jpeg", "webp"])
                
                # Promotion Settings
                col_prom, col_prom_date = st.columns(2)
                with col_prom:
                    is_promoted_val = st.checkbox("Is Promoted", value=bool(selected_rest["is_promoted"]))
                with col_prom_date:
                    prom_end_val = st.text_input("Promotion End Date (ISO 8601 or empty)", value=selected_rest["promotion_end_at"] or "")
                
                # Hidden/fixed values to retain
                osm_id = selected_rest["osm_id"]
                rest_id = selected_rest["id"]
                
                # Form Action Buttons
                col_btn1, col_btn2, col_btn3 = st.columns(3)
                
                with col_btn1:
                    approve = st.form_submit_button("✅ Approve (Mark Valid)", type="primary")
                with col_btn2:
                    reject = st.form_submit_button("❌ Reject (Mark Invalid)")
                with col_btn3:
                    save_pending = st.form_submit_button("💾 Save (Keep Pending)")
                    
                if approve or reject or save_pending:
                    # Input validation
                    if not name_val.strip():
                        st.error("Error: Restaurant Name is required.")
                    elif not (-90 <= lat_val <= 90) or not (-180 <= lng_val <= 180):
                        st.error("Error: Invalid coordinate bounds. Latitude must be -90 to 90, Longitude -180 to 180.")
                    else:
                        if uploaded_file is not None:
                            saved_path = save_uploaded_file(uploaded_file, rest_id)
                            cover_val = saved_path
                            
                        updated_data = {
                            "name": name_val,
                            "description": description_val if description_val.strip() else None,
                            "cuisine_type": cuisine_val if cuisine_val.strip() else None,
                            "price_level": price_val,
                            "lat": lat_val,
                            "lng": lng_val,
                            "address": address_val if address_val.strip() else None,
                            "cover_image_url": cover_val if cover_val.strip() else None,
                            "is_promoted": 1 if is_promoted_val else 0,
                            "promotion_end_at": prom_end_val if prom_end_val.strip() else None
                        }
                        
                        if approve:
                            database.update_restaurant_status(conn, rest_id, "valid", updated_data)
                            st.success(f"Approved and marked '{name_val}' as VALID!")
                            st.rerun()
                        elif reject:
                            database.update_restaurant_status(conn, rest_id, "invalid", updated_data)
                            st.warning(f"Rejected and marked '{name_val}' as INVALID.")
                            st.rerun()
                        elif save_pending:
                            database.update_restaurant_status(conn, rest_id, "pending", updated_data)
                            st.success(f"Saved changes for '{name_val}' as pending.")
                            st.rerun()
        
        with col_preview:
            st.markdown("### 🗺️ Location Preview")
            try:
                # Render interactive Folium Map
                m = folium.Map(location=[lat_val, lng_val], zoom_start=16)
                folium.Marker(
                    [lat_val, lng_val], 
                    popup=name_val, 
                    tooltip=name_val,
                    icon=folium.Icon(color='red', icon='cutlery', prefix='fa')
                ).add_to(m)
                st_folium(m, height=350, key="pending_map", use_container_width=True)
            except Exception as e:
                st.error(f"Could not load map: {e}")
                
            st.markdown("### 🖼️ Cover Image Preview")
            if uploaded_file is not None:
                st.image(uploaded_file, caption="Preview of uploaded image", use_container_width=True)
            elif cover_val:
                preview_img = load_preview_image(cover_val)
                if preview_img:
                    st.image(preview_img, caption=name_val, use_container_width=True)
                else:
                    st.warning("Cover image path/URL specified but file not found or invalid URL.")
            else:
                st.info("No cover image URL or preview available.")

# ==========================================
# ✅ TAB 2: APPROVED RESTAURANTS (EXPORT/EDIT)
# ==========================================
with tab_approved:
    approved_list = database.get_valid_restaurants(conn)
    
    if not approved_list:
        st.info("No approved restaurants found. Approve candidates in the 'Pending' tab first.")
    else:
        st.subheader(f"Approved Restaurants ({len(approved_list)})")
        
        # Display data table
        df = pd.DataFrame(approved_list)
        df_display = df[[
            "id", "name", "cuisine_type", "price_level", 
            "lat", "lng", "address", "is_promoted"
        ]]
        st.dataframe(df_display, use_container_width=True)
        
        # Select approved restaurant to edit
        selected_approved_name = st.selectbox("Select Restaurant to Edit/Re-evaluate", [r["name"] for r in approved_list])
        selected_approved = next(r for r in approved_list if r["name"] == selected_approved_name)
        
        st.subheader(f"✏️ Edit Approved Restaurant: {selected_approved['name']}")
        col_app_form, col_app_preview = st.columns([3, 2])
        
        with col_app_form:
            with st.form("approved_edit_form", clear_on_submit=False):
                # Edit fields
                app_name_val = st.text_input("Name (Required)", value=selected_approved["name"])
                app_description_val = st.text_area("Description", value=selected_approved["description"] or "")
                app_cuisine_val = st.text_input("Cuisine Type", value=selected_approved["cuisine_type"] or "")
                app_price_val = st.number_input("Price Level (1-4)", min_value=1, max_value=4, value=selected_approved["price_level"] or 2, step=1)
                
                # Coordinates
                col_app_lat, col_app_lng = st.columns(2)
                with col_app_lat:
                    app_lat_val = st.number_input("Latitude", value=float(selected_approved["lat"]), format="%.6f", key="app_lat")
                with col_app_lng:
                    app_lng_val = st.number_input("Longitude", value=float(selected_approved["lng"]), format="%.6f", key="app_lng")
                    
                app_address_val = st.text_input("Address", value=selected_approved["address"] or "")
                app_cover_val = st.text_input("Cover Image URL", value=selected_approved["cover_image_url"] or "", key="app_cover")
                app_uploaded_file = st.file_uploader("Or Upload Cover Image File", type=["png", "jpg", "jpeg", "webp"], key="app_upload")
                
                # Promotion Settings
                col_app_prom, col_app_prom_date = st.columns(2)
                with col_app_prom:
                    app_is_promoted_val = st.checkbox("Is Promoted", value=bool(selected_approved["is_promoted"]), key="app_is_prom")
                with col_app_prom_date:
                    app_prom_end_val = st.text_input("Promotion End Date (ISO 8601 or empty)", value=selected_approved["promotion_end_at"] or "", key="app_prom_date")
                
                # Action Buttons
                col_app_btn1, col_app_btn2 = st.columns(2)
                with col_app_btn1:
                    save_app_changes = st.form_submit_button("💾 Save Changes", type="primary")
                with col_app_btn2:
                    move_back = st.form_submit_button("📥 Move back to Pending")
                    
                if save_app_changes or move_back:
                    if not app_name_val.strip():
                        st.error("Error: Restaurant Name is required.")
                    elif not (-90 <= app_lat_val <= 90) or not (-180 <= app_lng_val <= 180):
                        st.error("Error: Invalid coordinate bounds.")
                    else:
                        app_rest_id = selected_approved["id"]
                        if app_uploaded_file is not None:
                            saved_path = save_uploaded_file(app_uploaded_file, app_rest_id)
                            app_cover_val = saved_path
                            
                        updated_data = {
                            "name": app_name_val,
                            "description": app_description_val if app_description_val.strip() else None,
                            "cuisine_type": app_cuisine_val if app_cuisine_val.strip() else None,
                            "price_level": app_price_val,
                            "lat": app_lat_val,
                            "lng": app_lng_val,
                            "address": app_address_val if app_address_val.strip() else None,
                            "cover_image_url": app_cover_val if app_cover_val.strip() else None,
                            "is_promoted": 1 if app_is_promoted_val else 0,
                            "promotion_end_at": app_prom_end_val if app_prom_end_val.strip() else None
                        }
                        
                        if save_app_changes:
                            database.update_restaurant_status(conn, app_rest_id, "valid", updated_data)
                            st.success(f"Saved changes for approved restaurant '{app_name_val}'!")
                            st.rerun()
                        elif move_back:
                            database.update_restaurant_status(conn, app_rest_id, "pending", updated_data)
                            st.info(f"Moved '{app_name_val}' back to Pending with updated details.")
                            st.rerun()
        
        with col_app_preview:
            st.markdown("### 🗺️ Location Preview")
            try:
                m_app = folium.Map(location=[app_lat_val, app_lng_val], zoom_start=16)
                folium.Marker(
                    [app_lat_val, app_lng_val], 
                    popup=app_name_val, 
                    tooltip=app_name_val,
                    icon=folium.Icon(color='green', icon='cutlery', prefix='fa')
                ).add_to(m_app)
                st_folium(m_app, height=300, key="approved_map", use_container_width=True)
            except Exception as e:
                st.error(f"Could not load map: {e}")
                
            st.markdown("### 🖼️ Cover Image Preview")
            if app_uploaded_file is not None:
                st.image(app_uploaded_file, caption="Preview of uploaded image", use_container_width=True)
            elif app_cover_val:
                preview_img_app = load_preview_image(app_cover_val)
                if preview_img_app:
                    st.image(preview_img_app, caption=app_name_val, use_container_width=True)
                else:
                    st.warning("Cover image path/URL specified but file not found or invalid URL.")
            else:
                st.info("No cover image URL or preview available.")
            
        st.divider()
        
        # EXPORTS SECTION
        st.subheader("📤 Export Validated Data")
        st.write("Generate and download the data to seed your main application's `global_restaurants` table.")
        
        col_json, col_sql = st.columns(2)
        
        # Prepare exports
        export_data = convert_to_export_format(approved_list)
        json_export_str = json.dumps(export_data, indent=2, ensure_ascii=False)
        sql_export_str = generate_sql_seed(approved_list)
        
        with col_json:
            st.markdown("### JSON Format")
            st.code(json_export_str[:300] + "\n..." if len(json_export_str) > 300 else json_export_str, language="json")
            
            # File system export button
            if st.button("Save JSON to data/validated_restaurants.json"):
                data_dir = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "data")
                json_path = os.path.join(data_dir, "validated_restaurants.json")
                with open(json_path, "w", encoding="utf-8") as f:
                    f.write(json_export_str)
                st.success(f"Saved to {json_path}!")
                
            # Download button
            st.download_button(
                label="📥 Download JSON File",
                data=json_export_str,
                file_name="validated_restaurants.json",
                mime="application/json"
            )
            
        with col_sql:
            st.markdown("### SQL Seed Format")
            st.code(sql_export_str[:300] + "\n..." if len(sql_export_str) > 300 else sql_export_str, language="sql")
            
            # File system export button
            if st.button("Save SQL to data/validated_restaurants.sql"):
                data_dir = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "data")
                sql_path = os.path.join(data_dir, "validated_restaurants.sql")
                with open(sql_path, "w", encoding="utf-8") as f:
                    f.write(sql_export_str)
                st.success(f"Saved to {sql_path}!")
                
            # Download button
            st.download_button(
                label="📥 Download SQL Seed File",
                data=sql_export_str,
                file_name="validated_restaurants.sql",
                mime="text/x-sql"
            )

# ==========================================
# ❌ TAB 3: REJECTED RESTAURANTS
# ==========================================
with tab_rejected:
    rejected_list = database.get_restaurants_by_status(conn, "invalid", selected_hood)
    
    if not rejected_list:
        st.info("No rejected restaurants found.")
    else:
        st.subheader(f"Rejected Restaurants ({len(rejected_list)})")
        
        df_rej = pd.DataFrame(rejected_list)
        df_rej_display = df_rej[[
            "id", "name", "cuisine_type", "lat", "lng", "address", "osm_id"
        ]]
        st.dataframe(df_rej_display, use_container_width=True)
        
        # Select and action
        selected_rejected_name = st.selectbox("Select Restaurant to Recover", [r["name"] for r in rejected_list])
        selected_rejected = next(r for r in rejected_list if r["name"] == selected_rejected_name)
        
        col_rec1, col_rec2 = st.columns(2)
        with col_rec1:
            if st.button("Restore to Pending"):
                database.update_restaurant_status(conn, selected_rejected["id"], "pending")
                st.info(f"Restored '{selected_rejected_name}' back to Pending status.")
                st.rerun()
        with col_rec2:
            if st.button("Delete Permanently"):
                cursor = conn.cursor()
                cursor.execute("DELETE FROM candidate_restaurants WHERE id = ?", (selected_rejected["id"],))
                conn.commit()
                st.warning(f"Deleted '{selected_rejected_name}' permanently from explorer database.")
                st.rerun()

# Close connection
conn.close()
