import os
import sys
import json
import argparse

# Add parent directory to path to import database
sys.path.append(os.path.dirname(os.path.abspath(__file__)))
import database

def convert_to_export_format(restaurants):
    """Converts SQLite integer booleans and other fields to final schema format."""
    exported = []
    for r in restaurants:
        r_dict = dict(r)
        # Convert SQLite is_promoted integer to boolean
        r_dict["is_promoted"] = True if r_dict.get("is_promoted") == 1 else False
        # Remove explorer specific fields
        r_dict.pop("validation_status", None)
        r_dict.pop("neighborhood", None)
        r_dict.pop("osm_id", None)
        exported.append(r_dict)
    return exported

def generate_sql_seed(restaurants):
    """Generates PostgreSQL INSERT statements matching the target global_restaurants schema."""
    if not restaurants:
        return ""
        
    sql_lines = [
        "-- SQL Seed Script for global_restaurants",
        "-- Generated by Neighborhood Explorer CLI Export",
        "INSERT INTO global_restaurants (",
        "    id, name, description, cuisine_type, price_level, lat, lng, address, ",
        "    cover_image_url, is_promoted, promotion_end_at, created_at, updated_at, ",
        "    likes_count, views_count",
        ") VALUES"
    ]
    
    value_rows = []
    for r in restaurants:
        def escape(val):
            if val is None:
                return "NULL"
            escaped = str(val).replace("'", "''")
            return f"'{escaped}'"
            
        r_id = escape(r.get("id"))
        name = escape(r.get("name"))
        desc = escape(r.get("description"))
        cuisine = escape(r.get("cuisine_type"))
        price = str(r.get("price_level")) if r.get("price_level") is not None else "NULL"
        lat = str(r.get("lat"))
        lng = str(r.get("lng"))
        addr = escape(r.get("address"))
        cover = escape(r.get("cover_image_url"))
        is_promoted = "true" if r.get("is_promoted") == 1 else "false"
        prom_end = escape(r.get("promotion_end_at"))
        created = escape(r.get("created_at"))
        updated = escape(r.get("updated_at"))
        likes = str(r.get("likes_count") or 0)
        views = str(r.get("views_count") or 0)
        
        row_str = f"    ({r_id}, {name}, {desc}, {cuisine}, {price}, {lat}, {lng}, {addr}, {cover}, {is_promoted}, {prom_end}, {created}, {updated}, {likes}, {views})"
        value_rows.append(row_str)
        
    sql_lines.append(",\n".join(value_rows) + ";")
    return "\n".join(sql_lines)

def main():
    parser = argparse.ArgumentParser(description="Export validated restaurants from explorer.db.")
    parser.add_argument(
        "--format", 
        choices=["json", "sql", "both"], 
        default="both",
        help="Export format: 'json', 'sql', or 'both' (default)"
    )
    parser.add_argument(
        "--output-dir",
        default=None,
        help="Directory to save exported files (defaults to explore/data)"
    )
    parser.add_argument(
        "--db-path",
        default=None,
        help="Path to the sqlite3 database file"
    )
    
    args = parser.parse_args()
    
    # Resolve paths
    explore_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    
    db_path = args.db_path or os.path.join(explore_root, "data", "explorer.db")
    output_dir = args.output_dir or os.path.join(explore_root, "data")
    
    if not os.path.exists(db_path):
        print(f"Error: Database file does not exist at {db_path}", file=sys.stderr)
        print("Please run the Streamlit app or insert some restaurants first.", file=sys.stderr)
        sys.exit(1)
        
    os.makedirs(output_dir, exist_ok=True)
    
    conn = database.get_db_connection(db_path)
    try:
        valid_restaurants = database.get_valid_restaurants(conn)
    except Exception as e:
        print(f"Error reading from database: {e}", file=sys.stderr)
        conn.close()
        sys.exit(1)
    conn.close()
    
    if not valid_restaurants:
        print("Warning: No approved ('valid') restaurants found in database. Nothing to export.")
        sys.exit(0)
        
    print(f"Found {len(valid_restaurants)} approved restaurants. Exporting...")
    
    if args.format in ["json", "both"]:
        json_path = os.path.join(output_dir, "validated_restaurants.json")
        export_data = convert_to_export_format(valid_restaurants)
        with open(json_path, "w", encoding="utf-8") as f:
            json.dump(export_data, f, indent=2, ensure_ascii=False)
        print(f"Saved JSON export to: {json_path}")
        
    if args.format in ["sql", "both"]:
        sql_path = os.path.join(output_dir, "validated_restaurants.sql")
        sql_content = generate_sql_seed(valid_restaurants)
        with open(sql_path, "w", encoding="utf-8") as f:
            f.write(sql_content)
        print(f"Saved SQL export to: {sql_path}")

if __name__ == "__main__":
    main()
